<?php
/**
 * Constant status
 */
define('STATUS_OK', 200);
define('STATUS_CREATED', 201);

define('STATUS_NO_CONTENT', 204);
define('STATUS_BAD_REQUEST', 400);
define('STATUS_UNAUTHORIZED', 401);
define('STATUS_FORBIDDEN', 403);
define('STATUS_NOT_FOUND', 404);
define('STATUS_METHOD_NOT_ALLOWED', 405);
define('STATUS_GONE', 410);
define('STATUS_UNPROCESSABLE_ENTITY', 422);
define('STATUS_INTERNAL_SERVER_ERROR', 500);
define('STATUS_NOT_IMPLEMENTED', 501);

?>