language: php

php:
  - 5.4
  - 5.5

script:
  - ./bin/make-phar
  - ./bin/make-test

notifications:
  recipients:
    - alban.linard@lsv.ens-cachan.fr
    - rokysaroi@yahoo.fr
  email:
    on_success: change
    on_failure: always
